name: Queue Monitor

on:
  schedule:
    - cron: '* * * * *'  # every 1 minute (GitHub minimum)
  workflow_dispatch:       # manual run option

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run monitor
        env:
          GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: node index.js
