name: Update Projects Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '* * * * *'   # every 1 minute (GitHub max)
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run script (5 sec loop inside)
        run: node index.js
        env:
          GRAFANA_SESSION: ${{ secrets.GRAFANA_SESSION }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
